### ISSUE TITLE
runtime error on -all argument with a supported website

### ISSUE THREAD

**Issue by TranKovak** [Girbons/comics-downloader#56]
**Describe the bug**
Hello, I got a `panic: runtime error: index out of range [4] with length 4`
when I try to download all the issue of a manga on mangareader.net
I can download specific issue but not all. I tried with 2 different manga.
maybe I use it wrongly.

**To Reproduce**
On widows 10 with the command
`comics-downloader.exe -all -format=cbz -url=http://www.mangareader.net/akira`
or 
`comics-downloader.exe -all -format=cbz -url=http://www.mangareader.net/mahou-sensei-negima`

**Expected behavior**
The program should create a cbz file of the manga with all issue.

**Screenshots**
```
>comics-downloader.exe -url=http://www.mangareader.net/akira -images-only -format=cbz -all
time="2020-04-14T17:58:19+02:00" level=info msg=Downloading... url="http://www.mangareader.net/akira"
panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
github.com/Girbons/comics-downloader/pkg/sites.(*Mangareader).GetInfo(0xb96030, 0xc00000e335, 0x20, 0x8, 0xc000107808, 0x74bdd5, 0x0)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/mangareader.go:104 +0x8a
github.com/Girbons/comics-downloader/pkg/sites.initializeCollection(0xc00010a200, 0x6, 0x8, 0xc000107f08, 0x8dc660, 0xb96030, 0x8, 0x0, 0x0, 0x0, ...)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/loader.go:21 +0xe8
github.com/Girbons/comics-downloader/pkg/sites.LoadComicFromSource(0xc000107f08, 0x4, 0xc0001079e8, 0x1, 0x1, 0x0)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/loader.go:75 +0x15c
github.com/Girbons/comics-downloader/cmd/app.download(0xc000107f08, 0x0)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/app/downloader.go:79 +0x593
github.com/Girbons/comics-downloader/cmd/app.Run(0xc000107f08)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/app/downloader.go:125 +0x90
main.main()
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/downloader/main.go:83 +0x24c
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version v0.22.2
 - Type CLI

Thank you for your time.

**Comment by Girbons** [comment]
Hey @TranKovak thanks for the report.

I will take a look asap

**Comment by TranKovak** [comment]
in the read me you say 
`Provide the comic url and use the -all flag. The url provided can be any issue of the comic, or the main comic page url.`

so I retried with this command
`comics-downloader.exe -url=http://www.mangareader.net/akira/1 -timeout 180 -format=cbz -all`
and its downloading all the issue, so it's juste the case where we provide only the main comic/manga page url that doesn't work.

and my excpected behavior is wrong, it make sense to have separte cbz, I think a new feature with cbc format could be great, but I will create a feature request for that to keep things clear here

in resume, this issue is
this doesn't work
`comics-downloader.exe -url=http://www.mangareader.net/akira -timeout 180 -format=cbz -all`

but this does
`comics-downloader.exe -url=http://www.mangareader.net/akira/1 -timeout 180 -format=cbz -all`

thank you again this program is awesome :)

**Comment by Girbons** [comment]
> comics-downloader.exe -url=http://www.mangareader.net/akira -timeout 180 -format=cbz -all

It should even work by providing the main comic page url, that's a thing to fix.
Also `timeout` parameter works only if `daemon` is set otherwise it does nothing, I should improve the readme.

> thank you again this program is awesome :)

I really appreciate that, thank you! :)

**Comment by Girbons** [comment]
Hey @TranKovak

 sorry for the delay 🙏, solved in [0.22.5](https://github.com/Girbons/comics-downloader/releases/tag/v0.22.5)!

**Comment by TranKovak** [comment]
Nice, thank you.

**Comment by jRimbault** [comment]
This is still happening for me on the latest release, sorry :/

**Comment by Girbons** [comment]
Hi @jRimbault thanks for reporting, I will take a look asap!
